"""File containing constants."""

# Path
PATH_DWIE = "data/DWIE/"
PATH_DWIE_BENCHMARK = PATH_DWIE + "benchmark/"
PATH_DWIE_COREF_WL = PATH_DWIE + "COREF/WL/dwie_data.json"
PATH_DWIE_COREF_WL_PREDICTIONS = PATH_DWIE + "COREF/WL"
PATH_DWIE_DATA = PATH_DWIE + "annotated_texts"
PATH_DWIE_GROUNDTRUTH_KBS = PATH_DWIE + "groundtruth"
PATH_DWIE_INIT_KB = PATH_DWIE + "init_kb.pickle"
PATH_DWIE_NER_FLAIR = PATH_DWIE + "NER/Flair/"
PATH_DWIE_TEST_FILES = PATH_DWIE + "test_files.pickle"
PATH_DWIE_NER_FLAIR_MODEL = (
    PATH_DWIE_NER_FLAIR + "taggers/sota-ner-flair/final-model.pt"
)
PATH_DWIE_NER_FLAIR_TEST = PATH_DWIE_NER_FLAIR + "predictions"

PATH_FLAIR_DATA = "data/models/NER/Flair/"
PATH_FLAIR_CHECKPOINT = PATH_FLAIR_DATA + "checkpoint.pt"
PATH_FLAIR_BASE_MODEL = PATH_FLAIR_DATA + "taggers/sota-ner-flair"

SENTENCE_END_CHAR = [".", '"', "?", "!"]

PRONOUNS = [
    "they",
    "he",
    "her",
    "his",
    "him",
    "their",
    "them",
    "we",
    "it",
    "i",
    "our",
    "its",
    "this",
    "you",
    "the",
]

UNWANTED_ENT_TYPES = [
    "footer",
    "none",
    "skip",
    "time",
    "money",
    "value",
    "role",
    "religion",
    "religion-x",
]

UNWANTED_TAG_TYPES = [
    "topic",
    "iptc",
    "gender",
    "sport",
    "slot",
    "meta",
    "sector",
    "sport_event",
    "policy",
]


DWIE_NER_TYPES = {
    "entity": 0,
    "language": 1,
    "location": 1,
    "waterbody": 2,
    "regio": 2,
    "facility": 2,
    "gpe": 2,
    "gpe0": 3,
    "gpe2": 3,
    "gpe1": 3,
    "organization": 1,
    "education_org": 2,
    "ngo": 2,
    "media": 2,
    "igo": 2,
    "so": 3,
    "party": 2,
    "company": 2,
    "sport_team": 2,
    "governmental_organisation": 2,
    "agency": 3,
    "armed_movement": 2,
    "person": 1,
    "deity": 2,
    "activist": 2,
    "journalist": 2,
    "gov_per": 2,
    "employee": 2,
    "politician": 2,
    "head_of_state": 3,
    "head_of_gov": 3,
    "minister": 3,
    "sport_player": 2,
    "artist": 2,
    "politics_per": 2,
    "manager": 2,
    "offender": 2,
    "misc": 1,
    "treaty": 2,
    "object": 2,
    "work_of_art": 2,
    "event": 1,
    "war": 2,
    "competition": 2,
    "sport_competition": 3,
    "ethnicity": 1,
    "other": 0,
    "loc-x": 1,
    "gpe0-x": 1,
    "gpe1-x": 1,
}

DWIE_NER_ONTOLOGY = {
    "entity": ["entity"],
    "language": ["language", "entity"],
    "location": ["location", "entity"],
    "loc": ["loc", "location", "entity"],
    "waterbody": ["waterbody", "location", "entity"],
    "facility": ["facility", "location", "entity"],
    "gpe": ["gpe", "location", "entity"],
    "gpe0": ["gpe0", "gpe", "location", "entity"],
    "gpe1": ["gpe1", "gpe", "location", "entity"],
    "gpe2": ["gpe2", "gpe", "location", "entity"],
    "regio": ["regio", "location", "entity"],
    "organization": ["organization", "entity"],
    "ngo": ["ngo", "organization", "entity"],
    "education_org": ["education_org", "organization", "entity"],
    "media": ["media", "organization", "entity"],
    "sport_team": ["sport_team", "organization", "entity"],
    "armed_mov": ["armed_movement", "organization", "entity"],
    "governmental_organisation": [
        "governmental_organisation",
        "organization",
        "entity",
    ],
    "agency": [
        "agency",
        "governmental_organisation",
        "organization",
        "entity",
    ],
    "armed_movement": ["armed_movement", "organization", "entity"],
    "company": ["company", "organization", "entity"],
    "igo": ["igo", "organization", "entity"],
    "so": ["so", "organization", "entity", "igo"],
    "party": ["party", "organization", "entity"],
    "person": ["person", "entity"],
    "deity": ["deity", "person", "entity"],
    "sport_player": ["sport_player", "person", "entity"],
    "artist": ["artist", "person", "entity"],
    "politics_per": ["politics_per", "person", "entity"],
    "manager": ["manager", "person", "entity"],
    "offender": ["offender", "person", "entity"],
    "employee": ["employee", "person", "entity"],
    "gov_per": ["gov_per", "person", "entity"],
    "journalist": ["journalist", "person", "entity"],
    "activist": ["activist", "person", "entity"],
    "politician": ["politician", "person", "entity"],
    "head_of_state": ["head_of_state", "person", "entity", "politician"],
    "head_of_gov": ["head_of_gov", "person", "entity", "politician"],
    "minister": ["minister", "person", "entity", "politician"],
    "ethnicity": ["ethnicity", "entity"],
    "event": ["event", "entity"],
    "competition": ["competition", "event", "entity"],
    "sport_competition": ["sport_competition", "competition", "event", "entity"],
    "misc": ["misc", "entity"],
    "work_of_art": ["work_of_art", "misc", "entity"],
    "object": ["object", "misc", "entity"],
    "treaty": ["treaty", "misc", "entity"],
    "other": ["other"],
    "gpe0-x": ["gpe0-x", "other"],
    "gpe1-x": ["gpe1-x", "other"],
    "loc-x": ["loc-x", "other"],
}
"""
DWIE_NER_TYPES = {
    "entity",
    "person",
    "work_of_art",
    "music_title",
    "misc",
    "organization",
    "armed_movement",
    "music_band",
    "other",
    "sport_org",
    "sport_player",
    "event",
    "war",
    "artist",
    "writer",
    "musician",
    "politician",
    "gpe",
    "gpe0",
    "gpe1",
    "gpe2",
    "gpe0-x",
    "party",
    "igo",
    "manager",
    "regio",
    "location",
    "company",
    "media",
    "technology",
    "business_per",
    "ideology",
    "facility",
    "offender",
    "advisor",
    "loc-x",
    "tv_award",
    "culture_misc",
    "treaty",
    "celestial_loc",
    "journalist",
    "ethnicity",
    "religion",
    "religion-x",
    "film_title",
    "criminal_org",
    "police_per",
    "head_of_state",
    "health_facility",
    "policy_institute",
    "politics_per",
    "district",
    "loc",
    "so",
    "science_per",
    "teacher",
    "education_org",
    "sport_team",
    "gpe1-x",
    "governmental_organisation",
    "minister",
    "island",
    "competition",
    "military_alliance",
    "head_of_gov",
    "sport_competition",
    "victim",
    "agency",
    "project",
    "award",
    "army",
    "music_band",
    "book_title",
    "language",
    "gov_per",
    "justice_per",
    "judge",
    "festive_event",
    "sport_head",
    "ngo",
    "ministry",
    "activist",
    "deity",
    "court",
    "politician_regional",
    "filmmaker",
    "health_disease",
    "sport_facility",
    "sport_coach",
    "military_facility",
    "politics_facility",
    "military_personnel",
    "royalty",
    "religion_misc",
    "history",
    "business_org",
    "business_misc",
    "clergy",
    "actor",
    "object",
    "character",
    "protest",
    "union",
    "researcher",
    "holiday",
    "waterbody",
    "research_center",
    "movement",
    "report",
    "politician_local",
    "police",
    "gpe2-x",
    "military_rebel",
    "religious_event",
    "education_student",
    "health_per",
    "product",
    "prison",
    "employee",
    "religion_org",
    "sport_award",
    "tv_title",
    "business_facility",
    "justice_misc",
    "street",
    "culture_per",
    "union_rep",
    "military_equipment",
    "film_award",
    "politician_national",
    "summit_meeting",
    "culture_facility",
    "justice_facility",
    "religion_facility",
    "advocacy",
    "politics_org",
    "education_per",
    "culture_title",
    "festival",
    "theatre_title",
    "military_mission",
    "market_index",
    "concept",
    "education_study",
    "scandal",
    "research_journal",
    "filmfestival",
    "union_member",
    "politics_misc",
    "incident",
    "trade_fair",
    "health_org",
    "mountain",
    "species",
    "exhibition_title",
    "book_award",
    "market_exchange",
    "politic_event",
    "storm",
    "relative",
    "case",
    "brand",
    "culture_org",
    "musical_title",
    "health_drug",
    "union_head",
    "politics_event",
    "police_org",
    "justice_org",
    "education_facility",
    "sport_referee",
}
"""
